# Generated by Django 4.1 on 2022-09-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userstickers_has'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstickers',
            name='id_complete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sticker'),
        ),
    ]
