# Generated by Django 4.1 on 2022-09-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_userstickers_repeated_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstickers',
            old_name='user',
            new_name='username',
        ),
    ]
