# Generated by Django 4.1 on 2022-09-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_user_userstickers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstickers',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
