# Generated by Django 4.1 on 2022-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_userstickers_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstickers',
            name='country',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userstickers',
            name='id_complete',
            field=models.CharField(max_length=6),
        ),
        migrations.DeleteModel(
            name='Sticker',
        ),
    ]
